title: Dr. Anandkumar Shantilal Patel
description: Academic Website
title: "Dr. Anandkumar Shantilal Patel"
name: "Dr. Anandkumar Shantilal Patel"
description: "Academic Website"
url: "https://dranandpatel.github.io"
baseurl: ""

repository: "dranandpatel/dranandpatel.github.io"

remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "default"

include:
  - _pages

plugins:
  - jekyll-include-cache

collections:
  teaching:
    output: true
  publications:
    output: true
